// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqgfnasvqzfkvqzbcguc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xZ2ZuYXN2cXpma3ZxemJjZ3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTMzMTksImV4cCI6MjA2MDM4OTMxOX0.aL6slYrFa788DpV_31TGHy6ZhqbpoL1TK-eQqJha0AU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);